#
# Configuration for environment
#
version: 1.0
app:
  version: ""
  
  instances:
    min: 1
    max: 1
    
  # Configure vCPU and indirectly memory resources for the application. 
  # The memory assigned to the application is directly proportional to the 
  # requested vCPU number multiplied by 4. For example, if cpu is set to 1, 4Gi
  # memory is allocated to the application; if cpu is set to 2, 8Gi of memory
  # is allocated to the application; and so on.  
  resources:
    # The vCPU number for the application. If not set, it defaults to 1 vCPU. 
    # The max number of vCPU that can be requested is 14.
    cpu: 1

  env:
    - name: SOME_ENV_VAR_NAME
      value: some_env_var_value

  # Set a list of Liberty variables for the application. 
  # Reference the variables in the server.xml using the 
  # ${some_liberty_variable_name} notation.
  variables:
    - name: some_liberty_variable_name
      value: some_liberty_variable_value
      
  # Set a list of the system properties for the Java runtime.
  systemProperties:
    - name: some_system_property_name
      value: some_system_property_value

  endpoints: public

  services:
    - crn: 'crn:v1:bluemix:public:mqcloud:us-east:a/26a5e866a11a5014f2eca2acab86f048:123019ac-5871-4f20-8e10-1207b38721fc::'

